### ISSUE TITLE
Cant change layer datasource in code

### ISSUE THREAD

**Issue by rouen-sk** [jbrwn/NET-Mapnik#25]
Hi, my styles and layers (without datasources) are defined in XML and loaded from it, but later I need to set datasources for layers programatically - and change it for different tiles. But the changes made to layer's properties doesnt seem to apply:

mapnikMap = new Map(256, 256);                        
mapnikMap.Load("mystyle.xml"));
mapnikMap.GetLayer("water").Datasource = new NETMapnik.Datasource(new Dictionary<string, object>{ /* datasource params - host, port, user, pass... */});
var ds = mapnikMap.GetLayer("water").Datasource; // NULL

Is this expected behaviour or bug? Is there any chance to do what I want? Thanks a lot!

**Comment by jbrwn** [comment]
This is expected.  GetLayer() returns copy of the layer.  

The Map class contains Clear() and AddLayer() methods but it does not really support the dynamic swapping of datasources that I think you are trying to achieve.  This is by design. Map objects are meant to be immutable in order to support async and multi threaded workflows.   

Here is a similar issue - mapnik/node-mapnik#467.   The recommended solution was to manage layers and styles in your own data structure and programmatically attach them to map objects as needed.  

Let me know if this helps you out.

**Comment by rouen-sk** [comment]
Thanks for clarification. So for now I am testing this solution:

- create "base" map object - load XML with styles, fonts.. but no layers
- for every tile i make clone of this base map, create and add layers with datasources in code, render tile, dispose map

seems pretty fast, overhead is negligible in comparision with queries duration, so I think I am fine, unless you have something important to say about this method :)

**Comment by jbrwn** [comment]
This seems like a good approach.  I'm going to close out this ticket but feel free to open it up if you run into anything else.  Thanks!
